var fruits = [
	"Yes.",
	"はい。",
	"Yes, please.",
	"はい、お願いします。",
	"Rather!",
	"そうです。",
	"Very well.",
	"いいですよ。",
	"OK.",
	"いよ！",
	"Yes, OK.",
	"はい、いよ！",
	"All right.",
	"結構です。",
	"Yes, all right.",
	"はい、結構です。",
	"Sure.",
	"もちろん。",
	"Yes, sure.",
	"はい、もちろんです。",
	"Of course.",
	"確かに",
	"Yes, of course.",
	"はい、やりもちろん。",
	"Certainly.",
	"もちろんです。",
	"Yes, certainly.",
	"はい、もちろんです。",
	"I will.",
	"そうします。",
	"I certainly will.",
	"確かにそうします。",
	"I would.",
	"そうします。",
	"I certainly would.",
	"はい、了解です。",
	"Wouldn’t I!",
	"。。。してないはいけないです。",
	"Wouldn’t I just!",
	"。。。してないはいけないです。",
	"I shouldn’t object.",
	"反対してないです。",
	"I shouldn’t object to ---- (sth)",
	"。。。反対したいです。",
	"I’d love it.",
	"いいですよ。",
	"I’d love to.",
	"いいですよ。",
	"I’d like to.",
	"いいですよ。",
	"I can’t refuse ----",
	"。。。断れない。",
	"---- can’t be refused.",
	"。。。断れません。",
	"I can hardly refuse ----",
	"。。。断り辛いです。",
	"---- can hardly be refused.",
	"。。。断り辛いです。",
	"No one can refuse ----",
	"だれも。。。断れません。",
	"Yes.",
	"はい。",
	"Yes, please.",
	"はい、了解です。",
	"Yes, thanks.",
	"はい、ありがとう。",
	"Why not? Thanks.",
	"なぜいけないか？ありがとう。",
	"I will, thanks.",
	"はい、了解です。ありがとう。",
	"Thank you. I will.",
	"ありがとうございます。私は。。。",
	"Good idea.",
	"良いアイデア。",
	"Yes, that’s a good idea.",
	"はい、いい考えね。",
	"All right.",
	"はい、結構です。",
	"All right. Let’s.",
	"結構です。。。。（やり）ましょう。",
	"Yes, let’s.",
	"はい、。。。（やり）ましょうか？",
	"Yes, let’s do that.",
	"はい、そうしましょう。",
	"I’d like to. Thanks.",
	"良いです。ありがとうございます。",
	"I’d very much like to. Thanks.",
	"結構です。ありがとうございます。",
	"I’d like to very much. Thanks.",
	"結構です。ありがとうございます。",
	"I’d love to. Thanks a lot.",
	"大好きです。どうもありがとうございます。",
	"I’d very much love to. Thanks a lot.",
	"大好きです。どうもありがとうございます。",
	"I’d love to very much. Thanks a lot.",
	"大好きです。どうもありがとうございます。",
	"That’s very kind of you. Thank you.",
	"どうもご丁寧に.頂きありがとうございます。",
	"You’re very kind. Thank you.",
	"どうもご親切さま。ありがとうございます。",
	"It’s very nice of you. Thank you.",
	"ご親切にどうもありがとう。",
	"That’d be very nice. Thank you.",
	"良かったです。ありがとうございます。",
	"Thank you for ----",
	"。。。に感謝しています。",
	"Thanks, that sounds nice.",
	"ありがとう。それは面白そうですね。",
	"Thanks, that sounds good.",
	"ありがとう。いいでしょね。",
	"Thanks, that sounds lovely.",
	"ありがとう。いいよ。",
	"Thanks, that sounds great.",
	"ありがとう、いいように見えます。",
	"Thanks for the invitation.",
	"お誘いありがとう。",
	"Thank you for your kind invitation.",
	"お招き頂きありがとうございます。",
	"It was very kind of you to invite me.",
	"お招き下さいましてありがとうございました。",
	"Thank you very much for your kind invitation to ---- (sp.) which I’m happy to accept.",
	"。。。に誘て頂き、誠にありがとうございます。",
	"I wish to accept with pleasure your invitation to ---- (sp.)",
	"喜んで招待を受けて頂き。。。",
	"I hardly know how to thank you for the great kindness and hospitality which you showed me.",
	"親切なおもてなしを頂き言葉で話せない程ありがとうございます。",
	"(Oh,) yes, please.",
	"はい、了解です。",
	"Cheers.",
	"良いですね。",
	"Lovely.",
	"素晴らしいですね。",
	"Terrific.",
	"凄いですね。",
	"Great.",
	"素敵です。",
	"Just what I needed.",
	"欲しかったです。",
	"I'd be delighted if ----",
	"。。。してくれば嬉しいです。",
	"If you're sure it's no trouble.",
	"お手数ですが。。。",
	"If you're sure it's no trouble to you.",
	"お手数ですが。。。",
	"If you're sure it's no trouble for you to ----",
	"お手数をおかけしますが",
	"Thanks.",
	"ありがとう。",
	"Thanks a lot.",
	"どうもありがとうございます。",
	"Thanks very much.",
	"どうもありがとうございました。",
	"Thank you.",
	"ありがとうございます。",
	"Thank you very much.",
	"誠にありがとうございます。",
	"Thank you very much.",
	"誠にありがとうございます。",
	"Thank you very much indeed.",
	"感謝しています。",
	"Thank you ever so much.",
	"感謝申し上げます。",
	"I don’t know how much I can thank you enough.",
	"感謝の言葉も見つかりません。",
	"I owe you much.",
	"謝恩です。",
	"It's very kind.",
	"良かったです。",
	"That's very kind.",
	"良いですね。",
	"It's very kind of you.",
	"ご親切に頂きます。",
	"It's very kind of you to ----",
	"ご親切に。。。して頂きます。",
	"You're very kind.",
	"ご親切様でした。",
	"You're most kind.",
	"ご親切様でした。",
	"That's extremely good.",
	"凄く良いですね。",
	"That's extremely good of you.",
	"あなたは凄く良いですね。",
	"That's extremely kind.",
	"ご親切に。",
	"That's extremely kind of you.",
	"ご親切様です。",
	"That's extremely thoughtful.",
	"思いやりのある。",
	"That's extremely thoughtful of you.",
	"思いやりのあるさん。",
	"I accept ----",
	"・・・を受け入れています。",
	"I accept that ----",
	"・・・と受け入れています。",
	"It is accepted that ----",
	"・・・と受け入れられています。",
	"It is accepted by many that ----",
	"大勢の人が・・・と受け入れています。",
	"---- is accepted by many.",
	"・・・が大勢の人より受け入れています。",
	"It is widely accepted that ----",
	"大勢の人より受け入れられていることは・・・です。",
	"It is reasonable to accept that ----",
	"・・・と受け入れているのが合理的です。",
	"It is highly acceptable that ----",
	"・・・ことは高度に受け入れることができます。",
	"I accept ---- as unquestionable.",
	"私は疑わずに・・・を受け入れています。",
	"---- is accepted as unquestionable.",
	"・・・が疑わずに受け入れられています。",
	"I accept as unquestionable that ----",
	"私は疑わずに・・・と受け入れています。",
	"I accept as unquestionable the idea that ----",
	"・・・という意見を疑わずに受け入れています。",
	"It is accepted as unquestionable that ----",
	"疑わずに受け入れられていることは・・・です。",
	"I accept ---- on the ground that ----",
	"・・・の理由で・・・を受け入れています。",
	"I accept it on the ground that ----",
	"・・・の理由でそれを受け入れています。",
	"---- is accepted on the ground that ----",
	"・・・が・・の理由で受け入れられています。",
	"It is accepted on the ground that ----",
	"それは・・・の理由で受け入れられています。",
	"I'm prepared to accept ----",
	"・・・を受け入れるための覚悟は十分にできています。",
	"I'm prepared to accept that ----",
	"・・・と受け入れるための覚悟は十分にできています。",
	"I accept it as meaning that ----",
	"・・・の意味でそれを受け入れています。",
	"I accept ---- as meaning that ----",
	"・・・の意味で・・・を受け入れています。",
	"---- is accepted as meaning that ----",
	"・・・が・・・の意味で受け入れられています。",
	"It is accepted as meaning that ----",
	"それが・・・の意味で受け入れられています。",
	"---- gains widespread acceptance.",
	"・・・が幅広い受諾を得ました。",
	"Admittedly, ----",
	"確かに、・・・。",
	"I admit ---- (sth.)",
	"・・・を認めています。",
	"I admit ---- (doing sth.)",
	"・・・をすることを認めています。",
	"I admit ---- (having done sth.)",
	"・・・をしたことを認めています。",
	"I admit to ---- (sth.)",
	"・・・を白状しています。",
	"I admit to ---- (doing sth.)",
	"・・・をしたことを白状しています。",
	"asdasda",
	'asdasdasdas',
	'asdasd'
  ];
var a = fruits.length;

//console.log(fruits.toLowerCase())

/**
 * Array filters items based on search criteria (query)
 */
function filterItems(query) {
	return fruits.filter(function(el) {
		return el.toLowerCase().indexOf(query.toLowerCase()) > -1;
	});
}
//console.log(Array.isArray(fruits));
//console.log(typeof filterItems('ap'));
console.log(filterItems('asd')); // ['apple', 'grapes']
// //console.log(filterItems('an')); // 'banana', 'mango', 'orange'][
